services:
  neo4j:
    image: neo4j:4.2.5
    expose:
      - "7687"
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: 'neo4j/secretgraph'
    volumes:
      - $HOME/neo4j/data:/data

  zookeeper:
    container_name: 'zookeeper'
    image: confluentinc/cp-zookeeper:6.1.1
    expose:
      - '2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    container_name: 'kafka'
    image: confluentinc/cp-kafka:6.1.1
    depends_on:
      - zookeeper
    ports:
      - '29092:9092'
    expose:
      - '9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
      KAFKA_MIN_INSYNC_REPLICAS: '1'

  rabbitmq:
      container_name: 'rabbitmq'
      image: 'rabbitmq:3.13.7-alpine'
      environment:
        RABBITMQ_DEFAULT_PASS: 'secret'
        RABBITMQ_DEFAULT_USER: 'myuser'
      ports:
        - '5672:5672'
        - '15672:15672'

  fraud-detection:
    container_name: 'fraud-detection'
    image: fraud-detection-rabbitmq-kafka:latest
    depends_on:
      - rabbitmq
      - kafka
      - neo4j
    ports:
      - '8080:8080'
    environment:
      SPRING_KAFKA_BOOTSTRAPSERVERS: 'kafka:9092'
      SPRING_KAFKA_CONSUMER_BOOTSTRAPSERVERS: 'kafka:9092'
      LOCATION_VERIFICATION_API_CALL: 'false'
      USER_INJECTION_SOURCE_NAME: 'user-injection'
      SPRING_NEO4J_URI: 'bolt://neo4j:7687'
      SPRING_NEO4J_AUTHENTICATION_USER: 'neo4j'
      SPRING_NEO4J_AUTHENTICATION_PASSWORD: 'secretgraph'
      SPRING_RABBITMQ_HOST: 'rabbitmq'
      SPRING_RABBITMQ_PORT: '5672'
      SPRING_RABBITMQ_USERNAME: 'myuser'
      SPRING_RABBITMQ_PASSWORD: 'secret'
      SPRING_PROFILES_ACTIVE: 'rabbitmq, kafka'